#cloud-config
package_update: false
package_upgrade: false

packages:
  - podman
  - buildah
  - skopeo
  - git
  - curl
  - wget
  - tmux
  - oci-utils

# Keep essential container configs
write_files:
  - path: /etc/containers/registries.conf
    content: |
      [registries.search]
      registries = ['docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com', 'registry.centos.org', 'quay.io', 'ghcr.io']
      [registries.insecure]
      registries = []
      [registries.block]
      registries = []
    owner: root:root
    permissions: '0644'

  - path: /etc/containers/storage.conf
    content: |
      [storage]
      driver = "overlay"
      runroot = "/run/containers/storage"
      graphroot = "/var/lib/containers/storage"
      [storage.options]
      additionalimagestores = []
      [storage.options.overlay]
      mountopt = "nodev,metacopy=on"
      size = "20G"
    owner: root:root
    permissions: '0644'

  - path: /etc/containers/containers.conf
    content: |
      [containers]
      log_driver = "journald"
      log_size_max = -1
      pids_limit = 2048
      [engine]
      cgroup_manager = "systemd"
      events_logger = "journald"
      runtime = "crun"
      [network]
      network_backend = "netavark"
    owner: root:root
    permissions: '0644'

  # Keep essential system optimizations
  - path: /etc/sysctl.d/99-podman-optimization.conf
    content: |
      vm.swappiness=10
      vm.dirty_ratio=15
      vm.dirty_background_ratio=5
      vm.max_map_count=262144
      net.core.rmem_max=16777216
      net.core.wmem_max=16777216
      net.ipv4.tcp_rmem=4096 87380 16777216
      net.ipv4.tcp_wmem=4096 65536 16777216
      net.ipv4.tcp_congestion_control=bbr
      fs.file-max=65536
      fs.inotify.max_user_watches=524288
    owner: root:root
    permissions: '0644'

  - path: /etc/systemd/journald.conf.d/podman.conf
    content: |
      [Journal]
      SystemMaxUse=500M
      SystemKeepFree=1G
      SystemMaxFileSize=100M
      RuntimeMaxUse=200M
      RuntimeKeepFree=500M
      RuntimeMaxFileSize=50M
      MaxRetentionSec=1week
    owner: root:root
    permissions: '0644'

runcmd:
  - sleep 10
  - dnf update -y --security --skip-broken || echo "Security update completed with warnings"
  - mkdir -p /opt/app /home/opc/.config/containers /home/opc/.config/systemd/user /etc/systemd/journald.conf.d
  - chown -R opc:opc /opt/app /home/opc/.config
  - |
    if [ -x /usr/local/bin/system-setup.sh ]; then
      /usr/local/bin/system-setup.sh || echo "System setup script completed with warnings"
    fi
  - |
    if [ -f /etc/sysctl.d/99-podman-optimization.conf ]; then
      sysctl -p /etc/sysctl.d/99-podman-optimization.conf || echo "Sysctl optimization completed with warnings"
    fi
  - systemctl daemon-reload && systemctl restart systemd-journald || echo "Systemd reload completed with warnings"
  - firewall-cmd --permanent --remove-service=cockpit || true
  - firewall-cmd --permanent --remove-service=dhcpv6-client || true
  - firewall-cmd --permanent --add-port=8081/tcp || echo "Firewall port addition completed with warnings"
  - firewall-cmd --reload || echo "Firewall reload completed with warnings"
  - rm -rf /var/cache/dnf/* /tmp/* /var/tmp/* || echo "Cleanup completed with warnings"
  - truncate -s 0 /var/log/messages /var/log/secure /var/log/cron || echo "Log truncation completed with warnings"
  - dnf update -y oci-utils || echo "OCI utils update completed with warnings"
  - echo "Cloud-init setup completed successfully"

final_message: |
  Cloud-init setup completed successfully! 
  All essential packages and configurations are installed.
  GitHub Actions will handle the remaining deployment steps.