version: '3.8'

services:
  # Infrastructure container for the web pod
  web-pod:
    image: k8s.gcr.io/pause:3.9
    ports:
      - "8081:8081"
    restart: unless-stopped

  # Nginx web server
  web:
    image: localhost/webserver-web:latest
    network_mode: "container:web-pod"
    volumes:
      - website-data:/usr/share/nginx/html/src:z
    depends_on:
      - web-pod
      - git-sync
    restart: unless-stopped

  # Tailscale for private networking - using official image
  tailscale:
    image: tailscale/tailscale:latest
    network_mode: "container:web-pod"
    privileged: true
    volumes:
      - tailscale-data:/var/lib/tailscale:z
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_HOSTNAME=${HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
    cap_add:
      - NET_ADMIN
    depends_on:
      - web-pod
    restart: unless-stopped

  # Git sync service
  git-sync:
    image: localhost/webserver-git-sync:latest
    volumes:
      - website-data:/git:z
    environment:
      - SYNC_INTERVAL=${SYNC_INTERVAL}
      - REPO_URL=${REPO_URL}
    restart: unless-stopped

  # Cloudflared tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro,z
      - ./cloudflared/tunnel-credentials.json:/etc/cloudflared/tunnel-credentials.json:ro,z
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped

volumes:
  website-data:
  tailscale-data:
