version: '3.8'

services:
  # Infrastructure container for the web pod
  web-pod:
    image: k8s.gcr.io/pause:3.9
    ports:
      - "8081:8081"
    restart: unless-stopped

  # Nginx web server
  web:
    image: ghcr.io/verilypete/webserver:latest
    network_mode: "container:web-pod"
    depends_on:
      - web-pod
    restart: unless-stopped

  # Tailscale for private networking - using official image
  tailscale:
    image: tailscale/tailscale:latest
    network_mode: "container:web-pod"
    privileged: true
    volumes:
      - tailscale-data:/var/lib/tailscale:z
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_HOSTNAME=${HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
    cap_add:
      - NET_ADMIN
    depends_on:
      - web-pod
    restart: unless-stopped

  # Cloudflared tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped

volumes:
  tailscale-data:
