apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tunnels.networking.cfargotunnel.com
spec:
  group: networking.cfargotunnel.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cloudflare:
                  type: object
                  properties:
                    accountId:
                      type: string
                    accountName:
                      type: string
                    secret:
                      type: string
                size:
                  type: integer
                  default: 1
                image:
                  type: string
                  default: cloudflare/cloudflared:latest
  scope: Namespaced
  names:
    plural: tunnels
    singular: tunnel
    kind: Tunnel
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tunnelbindings.networking.cfargotunnel.com
spec:
  group: networking.cfargotunnel.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tunnel:
                  type: object
                subjects:
                  type: array
                  items:
                    type: object
  scope: Namespaced
  names:
    plural: tunnelbindings
    singular: tunnelbinding
    kind: TunnelBinding
