name: Deploy to Production

on:
  repository_dispatch:
    types: [website-updated]
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout infrastructure code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to production server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ~/webserver
          
          echo "🚀 Starting production deployment..."
          
          # Create .env file directly
          cat > .env << 'ENV_EOF'
          HOSTNAME=${{ steps.hostname.outputs.hostname }}
          TAILSCALE_AUTH_KEY=${{ secrets.TAILSCALE_AUTH_KEY }}
          CLOUDFLARE_TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
          FORMSPREE_ENDPOINT=${{ secrets.FORMSPREE_ENDPOINT }}
          APP_PORT=8081
          APP_ENV=production
          ENV_EOF
          
          chmod 600 .env
         
          # Deploy script
          ./scripts/deploy.sh
          
          echo "✅ Production deployment complete!"
